name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.4-eclipse-temurin-17 # Utilisation de l'image Maven avec Java 17

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      - name: Afficher Bonjour
        run: echo "Bonjour"

      - name: Vérifier Maven
        run: mvn -version

      - name: Construire avec Maven (sans tests)
        run: mvn -B package -DskipTests --file pom.xml
